---
fixtures:
  repositories:
    auditd: "#{source_dir}/../auditd"
    common: "git://github.com/simp/pupmod-simp-common"
    concat: "git://github.com/simp/pupmod-simp-concat"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
    augeasproviders: "git://github.com/simp/augeasproviders"
    augeasproviders_core: "git://github.com/simp/augeasproviders_core"
    augeasproviders_grub: "git://github.com/simp/augeasproviders_grub"
  symlinks:
    pki: "#{source_dir}"
